### ISSUE TITLE
npm install tinder (error)

### ISSUE THREAD

**Issue by mattbajorek** [tinderjs/tinderjs#36]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tinder"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install tinder as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Here is the log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'tinder' ]
2 info using npm@3.9.3
3 info using node@v4.4.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData tinder
8 silly fetchNamedPackageData tinder
9 silly mapToRegistry name tinder
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'tinder',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'tinder',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/tinder
14 verbose request uri https://registry.npmjs.org/tinder
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:22:59 PM
17 verbose request id 505d850a68773666
18 verbose etag "BVAK5DHPJ1RKQXWZCP3S2B1IT"
19 http request GET https://registry.npmjs.org/tinder
20 http 304 https://registry.npmjs.org/tinder
21 verbose headers { date: 'Thu, 02 Jun 2016 18:22:48 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"BVAK5DHPJ1RKQXWZCP3S2B1IT"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-atl6231-ATL',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1464891768.140636,VS0,VE40',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 02 Jun 2016 18:22:48 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"BVAK5DHPJ1RKQXWZCP3S2B1IT"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-atl6231-ATL',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1464891768.140636,VS0,VE40',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/tinder from cache
24 verbose get saving tinder to C:\Users\bajor\AppData\Roaming\npm-cache\registry.npmjs.org\tinder\.cache.json
25 verbose correctMkdir C:\Users\bajor\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install tinder as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\bajor\Desktop\Development\tinderjs
45 error Windows_NT 10.0.10586
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tinder"
47 error node v4.4.5
48 error npm  v3.9.3
49 error code ENOSELF
50 error Refusing to install tinder as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by mrmayfield** [comment]
Can you tell me what steps you took to install it and produce this error?

**Comment by mattbajorek** [comment]
After I cloned the repo, I ran "npm install tinder" inside that repo directory

**Comment by mrmayfield** [comment]
just try running `$ npm install` without the tinder?

**Comment by mrmayfield** [comment]
Are you installing it as part of a module already called `tinder` ?

**Comment by mattbajorek** [comment]
Yes I thought there was more to install.  Thanks!

**Comment by mrmayfield** [comment]
No problem. Same thing happened to me once 😄 Price to pay for having the best module name lol.
