### ISSUE TITLE
Unable to Authorize

### ISSUE THREAD

**Issue by EnricoGiordano1992** [tinderjs/tinderjs#48]
Hi, I've a problem with ".authorize" method.
I've getted facebook token and id with authentication with passport, but when I call authorize I obtain this error:

`
"Failed to authenticate: Error calling Facebook: FB API Error HTTP status code: 400. Error message: (#12) bio field is deprecated for versions v2.8 and higher. Error code: undefined @lib/facebookClient.makeRequest#FB_UNKNOWN"
`

This is my code:

`

    var passportFacebookMiddleware = function (req, res, next) {
        var conf = {
            session: false,
            callbackURL: '/oauth/tinder/callback'
        };
        passport.authenticate('facebook', conf)(req, res, next);
    }

    app.get('/oauth/tinder/:route(post)', passportFacebookMiddleware);
    app.get('/oauth/tinder/:route(callback)',
        passport.authenticate('facebook', {
            callbackURL: '/oauth/tinder/callback',
            failureRedirect: '/api/error',
            authType: 'rerequest',
            scope: ['user_relationships', 'user_relationship_details', 'user_work_history', 'user_actions.music', 'user_education_history']
        }),
        function (req, res) {
            var client = new tinder.TinderClient();
            client.authorize(
                req.user.accessToken,
                req.user.id,                
                function(foo1, foo2) {
                    client.getAccount(function (error, data) {
                        res.send(JSON.stringify(data));
                    });
                });
        });

`

What's is wrong?

Thanks!

**Comment by mayeaux** [comment]
People are discussing a solution here: https://github.com/tinderjs/tinderjs/issues/44
