### ISSUE TITLE
Need to hit the passport api

### ISSUE THREAD

**Issue by mrmayfield** [tinderjs/tinderjs#5]
After a while of running a bot I run into 'recs timeout' message being returned from calling a get on new recommendations.

Based on this, I updated my location via the iOS client and Tinder Plus's Passport feature and voila, I was off and swiping (receiving recommendations) again. I think especially for something like data science and hardcore scraping this could really be a huge use @gcwelborn , I don't see docs for it online so I may need to sniff the endpoints out myself.

**Comment by stuwil** [comment]
Closed with #23.
