### ISSUE TITLE
Open question: Does Tinder keep track of recommendations? Or can you hit the IDs even w/o recommendation?

### ISSUE THREAD

**Issue by mrmayfield** [tinderjs/tinderjs#7]
Is it possible to collect a list of IDS and then hit them from a new account, even if you haven't been 'recommended' by Tinder? Assuming you fall within their discoverable range and they within yours (can you hack discovery ranges using this?)

**Comment by barczaG** [comment]
You can query users without recommendation. I've tested it!

**Comment by mrmayfield** [comment]
So if I have the user id of a beautiful girl, I can make a brand new account and then superlike her? 🤔 @barczaG

**Comment by barczaG** [comment]
I've tried it with simple like, but i guess that should work too :) @mrmayfield

**Comment by mrmayfield** [comment]
Muhahaha. I love hacking Tinder. Thanks for the protip 👌
